//go:build !ignore_autogenerated

// Hand-written DeepCopy (controller-gen unavailable in this scaffold). Regenerate
// with `controller-gen object` once the toolchain is wired into the build.
package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *AgentFleet) DeepCopyInto(out *AgentFleet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy returns a deep copy of the receiver.
func (in *AgentFleet) DeepCopy() *AgentFleet {
	if in == nil {
		return nil
	}
	out := new(AgentFleet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object deep copy of the receiver.
func (in *AgentFleet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *AgentFleetList) DeepCopyInto(out *AgentFleetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]AgentFleet, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *AgentFleetList) DeepCopy() *AgentFleetList {
	if in == nil {
		return nil
	}
	out := new(AgentFleetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object deep copy of the receiver.
func (in *AgentFleetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *AgentFleetSpec) DeepCopyInto(out *AgentFleetSpec) {
	*out = *in
	if in.TargetLabels != nil {
		m := make(map[string]string, len(in.TargetLabels))
		for k, v := range in.TargetLabels {
			m[k] = v
		}
		out.TargetLabels = m
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *AgentFleetSpec) DeepCopy() *AgentFleetSpec {
	if in == nil {
		return nil
	}
	out := new(AgentFleetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *AgentFleetStatus) DeepCopyInto(out *AgentFleetStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *AgentFleetStatus) DeepCopy() *AgentFleetStatus {
	if in == nil {
		return nil
	}
	out := new(AgentFleetStatus)
	in.DeepCopyInto(out)
	return out
}
