name: operator
on:
  push:
    branches: [main]
    paths:
      - "operator/**"
      - ".github/workflows/operator.yml"
      - ".github/workflows/_docker.yml"
  workflow_dispatch:
jobs:
  image:
    uses: ./.github/workflows/_docker.yml
    secrets: inherit
    with:
      project: operator
      prefix: operator
      context: operator
      dockerfile: operator/Dockerfile
