name: ssh-sidecar
on:
  push:
    branches: [main]
    paths:
      - "ssh-sidecar/**"
      - ".github/workflows/ssh-sidecar.yml"
      - ".github/workflows/_docker.yml"
  workflow_dispatch:
jobs:
  image:
    uses: ./.github/workflows/_docker.yml
    secrets: inherit
    with:
      project: ssh-sidecar
      prefix: sshd
      context: ssh-sidecar
      dockerfile: ssh-sidecar/Dockerfile
